name: ayana
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.9
  palette_generator: ^0.3.3+3
  get: ^4.6.6
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.6

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/
